# Krishna Adhikari's First Octave Tutorial Walkthrough Notebook

Reference: https://en.wikibooks.org/wiki/Octave_Programming_Tutorial/Vectors_and_matrices

<a id='octave_kernel'></a>
## Installing A Jupyter [Kernel for Octave](https://github.com/calysto/octave_kernel)

Prerequisites: Install Jupyter Notebook, and Octave. It is recommended that you also install gnuplot support in Octave for inline plotting.

```
Krishna's FunPrompt $ pip install --upgrade gnuplot_kernel
Requirement already up-to-date: gnuplot_kernel in ./anaconda/lib/python3.6/site-packages
Requirement already up-to-date: metakernel>=0.17.4 in ./anaconda/lib/python3.6/site-packages (from gnuplot_kernel)
Requirement already up-to-date: notebook>=4.0 in ./anaconda/lib/python3.6/site-packages (from gnuplot_kernel)
Requirement already up-to-date: pexpect>=4.2 in ./anaconda/lib/python3.6/site-packages (from metakernel>=0.17.4->gnuplot_kernel)
Requirement already up-to-date: ipykernel in ./anaconda/lib/python3.6/site-packages (from metakernel>=0.17.4->gnuplot_kernel)
Krishna's FunPrompt $ pip install octave_kernel
Collecting octave_kernel
  Downloading octave_kernel-0.26.2-py2.py3-none-any.whl
Requirement already satisfied: ipykernel in ./anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: metakernel>=0.18.0 in ./anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: jupyter-client>=4.3.0 in ./anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: pexpect>=4.2 in ./anaconda/lib/python3.6/site-packages (from metakernel>=0.18.0->octave_kernel)
Installing collected packages: octave-kernel
Successfully installed octave-kernel-0.26.2
Krishna's FunPrompt $ python -m octave_kernel.install
Krishna's FunPrompt 
```

**Before the kernel installation** I had done the following to try to get **[GNU Octave](https://www.gnu.org/software/octave)** installed in my machine.

(References https://www.gnu.org/software/octave/#install, http://wiki.octave.org/Octave_for_macOS) 

* Unsuccessfully tried Macports to do the basic installation. I used “sudo port install octave” command to do that. (Disk size changed from 106.81 GB to 105.94 GB but the installation failed - see below for some part of the installation std outuput) 
* Then tried ‘fink’ method too, but it didn’t work either.
* Finally, it worked when I tried with homebrew (Starting HD size 104.91 GB) using instructions from http://wiki.octave.org/Octave_for_macOS#Homebrew. I think it was successful (size down to 104.04 GB). Otherwise, the notebook kernell installation alone wouldn't have worked.

## Vectors and Matrices

### Row Vector

In [1]:
x = [1, 3, 2, 5]

x =

   1   3   2   5



### Column Vector

In [2]:
x = [1; 3; 2]

x =

   1
   3
   2



### Matrix
From this you can see that we use a comma to go to the next column of a vector (or matrix) and a semicolon to go to the next row. So, to specify a matrix, type in the rows (separating each entry with a comma) and use a semicolon to go to the next row.

In [4]:
A = [1, 1, 2; 3, 5, 8; 13, 21, 34]

A =

    1    1    2
    3    5    8
   13   21   34



### Operators

You can use the standard operators to

    add (+),
    subtract (-), and
    multiply (*)

matrices, vectors and scalars with one another. Note that the matrices need to have matching dimensions (inner dimensions in the case of multiplication) for these operators to work.

    The transpose operator is the single quote: '. To continue from the example in the previous section,


In [5]:
A'

ans =

    1    3   13
    1    5   21
    2    8   34



(Note: this is actually the complex conjugate transpose operator, but for real matrices this is the same as the transpose. To compute the transpose of a complex matrix, use the dot transpose (.') operator.)

    The power operator (^) can also be used to compute real powers of square matrices.


<a id='elemental_operations'></a>
## Elemental Operations

When you have two matrices of the same size, you can perform element by element operations on them. For example, the following divides each element of A by the corresponding element in B:

In [6]:
A = [1, 6, 3; 2, 7, 4]

A =

   1   6   3
   2   7   4



In [7]:
B = [2, 7, 2; 7, 3, 9]

B =

   2   7   2
   7   3   9



In [8]:
A ./ B

ans =

   0.50000   0.85714   1.50000
   0.28571   2.33333   0.44444



Note that you use the dot divide (./) operator to perform element by element division. There are similar operators for multiplication (.*) and exponentiation (.^).

Let's introduce a scalar for future use.

In [9]:
a = 5;

The dot divide operators can also be used together with scalars in the following manner.

C = a ./ B

returns a matrix, C where each entry is defined by

C<sub>ij</sub> = a / B<sub>ij</sub>   (Superscript/Subscript [Reference](https://answers.squarespace.com/questions/31514/how-do-you-add-subscript-text.html))

i.e. a is divided by each entry in B. Similarly

C = a .^ B

return a matrix with

C<sub>ij</sub> = a<sup>B<sub>ij</sub></sup> 

In [11]:
C = a ./ B

C =

   2.50000   0.71429   2.50000
   0.71429   1.66667   0.55556



In [13]:
C = a.^B

C =

        25     78125        25
     78125       125   1953125



In [16]:
5*5*5*5*5*5*5

ans =  78125


In [18]:
5**7

ans =  78125


## Indexing 

You can work with parts of matrices and vectors by indexing into them. You use a vector of integers to tell Octave which elements of a vector or matrix to use. For example, we create a vector

In [19]:
x = [1.2, 5, 7.6, 3, 8]

x =

   1.2000   5.0000   7.6000   3.0000   8.0000



Now to see the second element and the list of 1st, 3rd and 4th elements:

In [20]:
x(2)

ans =  5


In [21]:
x([1,3,4])

ans =

   1.2000   7.6000   3.0000



To select rows and columns from a matrix, we use the same principle. Let's define a matrix and select the 1st and 3rd rows and 2nd and 3rd columns:

In [22]:
A = [1, 2, 3; 4, 5, 6; 7, 8, 9]

A =

   1   2   3
   4   5   6
   7   8   9



In [24]:
A([1, 3], [2, 3])

ans =

   2   3
   8   9



The colon operator (:) can be used to select all rows or columns from a matrix. So, to select all the elements from the 2nd row, type

In [25]:
A(2, :)

ans =

   4   5   6



In [27]:
# Selecting all elements
A(:,:)

ans =

   1   2   3
   4   5   6
   7   8   9



## Ranges
We can also select a range of rows or columns from a matrix. We specify a range with

start:step:stop

You can actually type ranges at the Octave prompt to see what the results are. For example,

In [28]:
1:3:10

ans =

    1    4    7   10



The first number displayed was start, the second was start + step, the third, start + (2 * step). And the last number was less than or equal to stop.

Often, you simply want the step size to be 1. In this case, you can leave out the step parameter and type

In [30]:
1:1:10

ans =

    1    2    3    4    5    6    7    8    9   10



In [31]:
1:10

ans =

    1    2    3    4    5    6    7    8    9   10



As you can see, the result of a range command is simply a vector of integers. We can now use this to index into a vector or matrix. To select the 2 × 2 submatrix at the top left of A, use


In [32]:
 A(1:2, 1:2)

ans =

   1   2
   4   5



Finally, there is a keyword called end that can be used when indexing into a matrix or vector. It refers to the last element in the row or column. For example, to see the last column in a Matrix, you can use

In [33]:
A(:,end)

ans =

   3
   6
   9



<a id='functions'></a>
## Functions

The following functions can be used to create and manipulate matrices.
### Creating matrices

* tril(A) returns the lower triangular part of A.

* triu(A) returns the upper triangular part of A.

* eye(n) returns the n × n  identity matrix. You can also use eye(m, n) to return m × n rectangular identity matrices.

* ones(m, n) returns an m × n  matrix filled with 1s. Similarly, ones(n) returns n × n square matrix.

* zeros(m, n) returns an m × n  matrix filled with 0s. Similarly, zeros(n) returns n × n square matrix.

* rand(m, n) returns an m × n  matrix filled with random elements drawn uniformly from [ 0 , 1 ). Similarly, rand(n) returns n × n  square matrix.

* randn(m, n) returns an m × n  matrix filled with normally distributed random elements.

* randperm(n) returns a row vector containing a random permutation of the numbers 1 , 2 , … , n.

* diag(x) or diag(A). For a vector, x, this returns a square matrix with the elements of x on the diagonal and 0s everywhere else. For a matrix, A, this returns a vector containing the diagonal elements of A. For example,


In [34]:
x = diag(A)

x =

   1
   5
   9



In [37]:
diag(x)

ans =

Diagonal Matrix

   1   0   0
   0   5   0
   0   0   9



In [36]:
x = diag(A)

x =

   1
   5
   9



* linspace(a, b, n) returns a vector with n values, such that the first element equals a, the last element equals b and the difference between consecutive elements is constant. The last argument, n, is optional with default value 100.

In [38]:
linspace(2, 4, 2)

ans =

   2   4



In [39]:
linspace(2, 4, 4)

ans =

   2.0000   2.6667   3.3333   4.0000



In [40]:
linspace(2, 4, 6)

ans =

   2.0000   2.4000   2.8000   3.2000   3.6000   4.0000



logspace(a, b, n) returns a vector with n values, such that the first element equals 10<sup>a</sup>, the last element equals 10<sup>b</sup> and the ratio between consecutive elements is constant. The last argument, n is optional with default value 50.

In [41]:
logspace(2, 4, 2)

ans =

     100   10000



In [42]:
logspace(2, 4, 4)

ans =

   1.0000e+02   4.6416e+02   2.1544e+03   1.0000e+04



In [43]:
logspace(2, 4, 5)

ans =

   1.0000e+02   3.1623e+02   1.0000e+03   3.1623e+03   1.0000e+04



## Other matrices

There are some more functions for creating special matrices. These are

    hankel (Hankel matrix),
    hilb (Hilbert matrix),
    invhilb (Inverse of a Hilbert matrix),
    sylvester_matrix (Sylvester matrix) - In v3.8.1 there is a warning: sylvester_matrix is obsolete and will be removed from a future version of Octave; please use hadamard(2^k) instead,
    toeplitz (Toeplitz matrix),
    vander (Vandermonde matrix).

Use help to find out more about how to use these functions.

## Changing matrices

* fliplr(A) returns a copy of matrix A with the order of the columns reversed, for example,


In [44]:
A = [1, 2, 3, 4; 5, 6, 7, 8; 9, 10, 11, 12] 

A =

    1    2    3    4
    5    6    7    8
    9   10   11   12



In [45]:
fliplr(A)

ans =

    4    3    2    1
    8    7    6    5
   12   11   10    9



* flipud(A) returns a copy of matrix A with the order of the rows reversed, for example,

In [46]:
flipud(A)

ans =

    9   10   11   12
    5    6    7    8
    1    2    3    4



* rot90(A, n) returns a copy of matrix A that has been rotated by (90n)° counterclockwise. The second argument, n is optional with default value 1, and it may be negative.

In [47]:
rot90(A)

ans =

    4    8   12
    3    7   11
    2    6   10
    1    5    9



* reshape(A, m, n) creates an m × n  matrix with elements taken from A. The number of elements in A has to be equal to  mn. The elements are taken from A in column major order, meaning that values in the first column ( A<sub>11</sub> , … , A<sub> m1</sub> ) are read first, then the second column ( A<sub>12</sub> , … , A<sub> m2</sub> ), etc.

In [48]:
reshape(A,2,6)

ans =

    1    9    6    3   11    8
    5    2   10    7    4   12



* sort(x) returns a copy of the vector x with the elements sorted in increasing order.

In [51]:
x = rand(1, 6)

x =

   0.59588   0.16018   0.63792   0.29903   0.87505   0.22355



In [52]:
sort(x)

ans =

   0.16018   0.22355   0.29903   0.59588   0.63792   0.87505



In [53]:
sort(rot90(A))

ans =

    1    5    9
    2    6   10
    3    7   11
    4    8   12



### Linear algebra
For a description of more operators and functions that can be used to manipulate vectors and matrices, find eigenvalues, etc., see the [Linear algebra](https://en.wikibooks.org/wiki/Octave_Programming_Tutorial/Linear_algebra) section.